# Generated by Django 5.1.7 on 2025-05-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription_groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitaine', models.CharField(max_length=255)),
                ('nom_equipe', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=50)),
                ('effectif', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('valide', 'Validé')], default='en attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription_solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=50)),
                ('groupe', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('valide', 'Validé')], default='en attente', max_length=20)),
            ],
        ),
    ]
