# Generated by Django 5.1.7 on 2025-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inscription_groupe_inscription_solo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription_groupe',
            name='nom_equipe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription_solo',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
